from .count_wednesdays import process as count_wednesdays
from .extract_comments import process as extract_comments
from .extract_credit_card import process as extract_credit_card
from .extract_email import process as extract_email
from .extract_gold_sales import process as extract_gold_sales
from .extract_logs import process as extract_logs
from .format_markdown import process as format_markdown
from .index_markdown import process as index_markdown
from .sort_contacts import process as sort_contacts
